### ISSUE TITLE
Update Ingress-Template for Confluence and Jira chart to current Kubernetes standards

### ISSUE THREAD

**Issue by GeraldST** [javimox/helm-charts#70] opened 2022-01-17 13:05 UTC
Thank you very much for your Confluence+Jira charts!

I have two suggestions to adapt the ingress-chart-template to newest Kubernetes specifications and I hope you can implement those changes:

**1) Use API version networking.k8s.io/v1 instead of networking.k8s.io/v1beta1**

**Problem**: Currently deploying the ingress gives a warning:
W0116 17:47:29.227333   15024 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

The API version networking.k8s.io/v1beta1 for ingress is deprecated with Kubernetes 1.22

See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22 

**Solution**: Pls. use API version networking.k8s.io/v1 instead

**2) Implement ingressClassName field**

**Problem:** Since Kubernetes 1.18 there is a new field ingressClassName which is the official way to specify the IngressClass resource that contains additional Ingress configuration, instead of the former never formally defined annotation kubernetes.io/ingress.class. Since Kubernetes 1.22 this is the standard way - the old annotation form is deprecated.

Currently it is not possible to specify this ingressClassName as there is no parameter for it in the chart and no placeholder in the ingress template.

See: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class
And: https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/

**Solution:** Pls. implement a parameter for spec.ingressClassName to define value for this field.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: nginx

Thank you!
Gerald

**Comment by javimox** [comment] 2022-02-11 13:07
@GeraldST : thank you for the heads up! It sounds good. I'll try to get it done soon but I can't promise.
You can create a PR with the changes, though. That'd would be faster.

Thanks!

**Comment by javimox** [comment] 2022-04-26 08:18
This issue should be fixed with @schnapsidee solutions. Thanks again.

@GeraldST : I'd close this issue then. Do you get the chance to test the changes of today releases yourself?

Cheers,

**Comment by schnapsidee** [comment] 2022-04-27 08:13
No problem. I just deployed to Prod and everything works as intended.

**Closed** 2022-04-27 11:20 UTC
